// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHCFukXyIY019xNMrelTeBU_z_5_e7z0',
    appId: '1:1026502954141:web:3dbe80d4f293a00c931874',
    messagingSenderId: '1026502954141',
    projectId: 'garbage-scan-e8e02',
    authDomain: 'garbage-scan-e8e02.firebaseapp.com',
    storageBucket: 'garbage-scan-e8e02.appspot.com',
    measurementId: 'G-KST2W0GRKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhBiiDemS7PMTd_QSjOqeiaYY9vfnu6fU',
    appId: '1:1026502954141:android:2e3a389be9d89f70931874',
    messagingSenderId: '1026502954141',
    projectId: 'garbage-scan-e8e02',
    storageBucket: 'garbage-scan-e8e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcXJuMrfPU4EijlBGzvduLtDrJL3hvDt4',
    appId: '1:1026502954141:ios:efec1be448db264b931874',
    messagingSenderId: '1026502954141',
    projectId: 'garbage-scan-e8e02',
    storageBucket: 'garbage-scan-e8e02.appspot.com',
    androidClientId:
        '1026502954141-be57l2et3rvcknipj47fa86gl4fm3t49.apps.googleusercontent.com',
    iosClientId:
        '1026502954141-l4v6ip8mjhk3pg1mi3kpk4tlhbsbtqcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageClassified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcXJuMrfPU4EijlBGzvduLtDrJL3hvDt4',
    appId: '1:1026502954141:ios:ea3c412bea17106f931874',
    messagingSenderId: '1026502954141',
    projectId: 'garbage-scan-e8e02',
    storageBucket: 'garbage-scan-e8e02.appspot.com',
    androidClientId:
        '1026502954141-be57l2et3rvcknipj47fa86gl4fm3t49.apps.googleusercontent.com',
    iosClientId:
        '1026502954141-uqb9ve45ijkbbqlkhvrttih2ubgpabf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageClassified.RunnerTests',
  );
}
