// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSD0Wf0P6lu9_NF2Q-t76oRCDmRHzwyJc',
    appId: '1:44088459127:web:ee3b295001e5590abb6b72',
    messagingSenderId: '44088459127',
    projectId: 'garbage-scan-2b3a3',
    authDomain: 'garbage-scan-2b3a3.firebaseapp.com',
    storageBucket: 'garbage-scan-2b3a3.appspot.com',
    measurementId: 'G-Q0392L0WLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-DhrkBP7M8Dp92anoLTf3DnVRdAwj3k',
    appId: '1:44088459127:android:1cab51d0b7344cbdbb6b72',
    messagingSenderId: '44088459127',
    projectId: 'garbage-scan-2b3a3',
    storageBucket: 'garbage-scan-2b3a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4CDkvj34G21xiut6NN98-prpX4NOOSWU',
    appId: '1:44088459127:ios:e662a0f52c36e40abb6b72',
    messagingSenderId: '44088459127',
    projectId: 'garbage-scan-2b3a3',
    storageBucket: 'garbage-scan-2b3a3.appspot.com',
    iosBundleId: 'com.example.garbageClassified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4CDkvj34G21xiut6NN98-prpX4NOOSWU',
    appId: '1:44088459127:ios:f0442a86de53ebb8bb6b72',
    messagingSenderId: '44088459127',
    projectId: 'garbage-scan-2b3a3',
    storageBucket: 'garbage-scan-2b3a3.appspot.com',
    iosBundleId: 'com.example.garbageClassified.RunnerTests',
  );
}
